require:
- rubocop-rails
- rubocop-rspec

AllCops:
  Exclude:
    - "bin/*"
    - "db/*"
    - "config/*/*"
    - "Guardfile"
    - "Rakefile"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  # EnforcedStyle: compact

Metrics/AbcSize:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
