# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    config: './rubocop.yml'

files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "README.md"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"