# frozen_string_literal: true
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

ActiveRecord::Base.connection.reset_pk_sequence!('specialities')
specialities = Speciality.create([{ speciality: 'General Doctor' },
                                  { speciality: 'Skin & Hair' },
                                  { speciality: 'Child Care' },
                                  { speciality: 'Women\'s Health' },
                                  { speciality: 'Dentist' },
                                  { speciality: 'ENT' },
                                  { speciality: 'Homeopathy' },
                                  { speciality: 'Ayurveda' },
                                  { speciality: 'Cardiac' },
                                  { speciality: 'Psychiatry' }])

ActiveRecord::Base.connection.reset_pk_sequence!('doctors')
doctors = Doctor.create([{ speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id },
                         { speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id },
                         { speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id },
                         { speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id },
                         { speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id },
                         { speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id },
                         { speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id },
                         { speciality_id: Speciality.find(1).id },
                         { speciality_id: Speciality.find(2).id },
                         { speciality_id: Speciality.find(3).id },
                         { speciality_id: Speciality.find(4).id },
                         { speciality_id: Speciality.find(5).id },
                         { speciality_id: Speciality.find(6).id },
                         { speciality_id: Speciality.find(7).id },
                         { speciality_id: Speciality.find(8).id },
                         { speciality_id: Speciality.find(9).id },
                         { speciality_id: Speciality.find(10).id }])


# doctors Accounts
ActiveRecord::Base.connection.reset_pk_sequence!('accounts')
accounts = Account.create(
  [
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(1) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(2) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(3) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(4) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(5) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(6) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(7) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(8) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(9) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(10) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(11) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(12) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(13) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(14) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(15) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(16) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(17) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(18) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(19) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(20) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(21) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(22) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(23) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(24) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(25) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(26) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(27) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(28) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(29) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(30) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(31) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(32) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(33) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(34) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(35) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(36) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(37) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(38) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(39) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(40) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(41) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(42) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(43) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(44) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(45) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(46) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(47) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(48) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(49) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(50) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(61) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(62) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(63) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(64) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(65) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(66) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(67) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(68) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(69) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(70) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(71) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(72) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(73) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(74) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(75) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(76) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(77) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(78) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(79) },
    { first_name: Faker::Name.name.split.last, last_name: Faker::Name.name.split.last, email: Faker::Internet.unique.email, password: Faker::Internet.password, role: Doctor.find(80) },
  ])